version: 0.2

env:
  secrets-manager:
     GIT_USERNAME: SF-SDN-GIT-TOKEN:GIT_USERNAME
     GIT_PASSWORD: SF-SDN-GIT-TOKEN:GIT_PASSWORD

phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
        - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        - chmod 700 get_helm.sh
        - ./get_helm.sh
        - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl
        - chmod +x ./kubectl
        - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
        - kubectl version --short --client
  pre_build:
    commands:
        - git clone https://"$GIT_USERNAME":"$GIT_PASSWORD"@github.com/sf-sdn/cni-deployer.git cni-deployer
        - cd cni-deployer
        - git fetch origin "$GIT_BRANCH"
        - git checkout "$GIT_BRANCH"
  build:
    commands:
        - MANIFEST_PATH="$CODEBUILD_SRC_DIR/aws/$ENV_NAME/$MANIFEST_FILENAME"
        - make setup
        - python src/helm_template_generator.py --manifest_path $MANIFEST_PATH
        - python src/eks_dataplane_deploy.py --deploy-stage validate --manifest $MANIFEST_PATH --direction inbound
        - kubectl get pods -n cni-inbound
        - python src/eks_dataplane_deploy.py --deploy-stage validate --manifest $MANIFEST_PATH --direction outbound
        - kubectl get pods -n cni-outbound
artifacts:
  files:
    - '**/*'
  name: $(date -u +"%Y-%m-%d %H:%M:%S")