version: 0.2

env:
  secrets-manager:
    GIT_USERNAME: SF-SDN-GIT-TOKEN:GIT_USERNAME
    GIT_PASSWORD: SF-SDN-GIT-TOKEN:GIT_PASSWORD

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
    commands:
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
      - unzip terraform_"$TF_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - cd cni-deployer
      - MANIFEST_PATH="$CODEBUILD_SRC_DIR/aws/$ENV_NAME/$MANIFEST_FILENAME"
      - eval "$(python Infrastructure/deployer/deployment_helper.py -c export_to_env -manifest $MANIFEST_PATH)"
      - GIT_BRANCH="${TF_VAR_deployer_repo_branch:-master}"
      - GIT_COMMIT="${TF_VAR_deployer_repo_commit:-HEAD}"
      - git fetch origin "$GIT_BRANCH"
      - git checkout "$GIT_BRANCH"
      - git checkout "$GIT_COMMIT"
  build:
    commands:
      - MODULE_PATH="$CODEBUILD_SRC_DIR/cni-deployer/Infrastructure/provider/aws/$MODULE_NAME"
      - VPC_SUFFIX_LIST=$(python Infrastructure/deployer/deployment_helper.py -c "print_outbound_vpc_suffixes" -manifest "$MANIFEST_PATH")
      - |
        for vpc_suffix in $VPC_SUFFIX_LIST;
        do
          python Infrastructure/deployer/deploy.py -c apply -module "$MODULE_PATH" -manifest "$MANIFEST_PATH" -automation -manifest_override "{ \"vpc_suffix\": \"$vpc_suffix\"}"
        done
