---
region: 'us-west-2'
env_name: test
deployment_id: 'agajjala'
tags:
  team: CNI
artifact_bucket: ''
lambda_layer_s3_key: ''
lambda_function_s3_key: ''
monitoring:
  image: 985884022631.dkr.ecr.us-west-2.amazonaws.com/cni-monitoring
  version: '3'
dataplane_inbound:
  image: 985884022631.dkr.ecr.us-west-2.amazonaws.com/cni-nginx-proxy-inbound
  version: '19'
dataplane_outbound:
  image: 985884022631.dkr.ecr.us-west-2.amazonaws.com/cni-nginx-proxy-outbound
  version: '19'
loadbalancer:
  internalLoadBalancer: "no"
