region: us-west-2
env_name: dev
deployment_id: stage1
tags:
  region: us-west-2
  env_name: dev
  deployment_id: stage1
outbound_vpc_cidr: 10.20.8.0/22
lambda_layer_s3_key: zip/cni_common-udmalpe-b062e5d7-f07f-4097-93ba-d6e5d91c55cb.zip
lambda_function_s3_key: zip/api_v1.zip
lambda_memory_size: 2048
authorizer_id: 08alb1
dataplane_inbound:
  image: 985884022631.dkr.ecr.us-west-2.amazonaws.com/cni-nginx-proxy-inbound
  version: '19'
dataplane_outbound:
  image: 985884022631.dkr.ecr.us-west-2.amazonaws.com/cni-nginx-proxy-outbound
  version: '19'
outbound_vpcs_config:
  vpcs_count: 2
  vpc_cidrs:
    - 10.20.8.0/22
    - 10.20.12.0/22