region: us-west-2
env_name: dev
deployment_id: stage1
tags:
  region: us-west-2
  env_name: dev
  deployment_id: stage1
lambda_layer_s3_key: zip/cni_common-udmalpe-b062e5d7-f07f-4097-93ba-d6e5d91c55cb.zip
lambda_function_s3_key: zip/api_v1.zip
lambda_memory_size: 2048
outbound_vpc_cidr: 10.20.8.0/22

