# Default values for cni-inbound.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
env_name: dev
deployment_id: dev
region: us-west-2
namespace: cni-inbound
replicaCount: 3
# Following sets a config on the pod of the same name
# This should be set roughly equal to the max connection lifespan expected
# in order for clients to not receive error codes during pod termination
terminationGracePeriodSeconds: 300

aws:
  ec2:
    metadata_url: "http://169.254.169.254/latest"

direction: inbound

dataplane_inbound:
  image: 985884022631.dkr.ecr.us-west-2.amazonaws.com/cni-nginx-proxy-inbound
  version: "latest"

metrics_exporter:
  image: 985884022631.dkr.ecr.us-west-2.amazonaws.com/cni-metrics-exporter
  version: 'latest'

cluster_autoscaler:
  image: k8s.gcr.io/cluster-autoscaler
  version: "v1.14.7"

cluster_autoscaler_resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    cpu: 100m
    memory: 300Mi

metrics_exporter_resources:
  requests:
    cpu: 0.5
  limits:
    cpu: 1

image:
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# This currently assumes AWS, we can revisit if we have to be on other
# substrates
loadbalancer:
  type: nlb
  internalLoadBalancer: "yes"
  proxyProtocol: "*"

service:
  type: LoadBalancer

# Value should be overriden in aws with ${ #stage(\"pre_deploy\").outputs.kubernetesServiceAccountName }
serviceAccount:
  name: cni-inbound

resources:
  requests:
    cpu: 1000m
  limits:
    cpu: 12000m

nodeSelector: {}

tolerations: []

affinity: {}
enable_sitebridge: false
lambdas:
  - authorizer
  - custom-metrics
  - ddb-stream-fanout
  - in-pl-event-handler
  - in-pl-stream
  - in-supervisor
  - info-inbound-GET
  - info-outbound-GET
  - out-pl-event-handler
  - out-pl-stream
  - out-supervisor
  - pl-inbound-get
  - pl-inbound-item-DELETE
  - pl-inbound-item-GET
  - pl-inbound-item-PATCH
  - pl-inbound-item-PUT
  - pl-outbound-GET
  - pl-outbound-POST
  - pl-outbound-item-GET
  - pl-outbound-item-POST
  - pl-outbound-item-DELETE
  - pl-outbound-item-PATCH
